### PR TITLE
Tests: Catch an earlier QCOMPARE failure in compare()

### PR DESCRIPTION
**Pull request by thiagomacieira**
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>

### CODE REVIEW

**Comment by lpereira** [comment]
Looks harmless enough, but what's the story here?

**Comment by thiagomacieira** [comment]
> Looks harmless enough, but what's the story here?

`QCOMPARE` macro has a return in case of failure. If a test fails inside the `encodeOne` function, we log that error, but were proceeding to perform more tests (which could fail again and produce more errors).

**Comment by lpereira** [comment]
That would look nice in the commit message :)

+1 for the patch

**Comment by thiagomacieira** [comment]
> That would look nice in the commit message :) +1 for the patch

Ok. Sorry, it was obvious to me :-)

**Pull request merged**
