### PR TITLE
Added the method cbor_encode_raw to the API

### PR DESCRIPTION
**Pull request by TSonono**
This method allows for writing raw data directly to the encoding buffer. Particularly useful if you have something stored as CBOR encoded data and want to push it to your encoding stream/buffer.

### CODE REVIEW

**Comment by thiagomacieira** [comment]
Oh, please include "Fixes #162" in the commit message somewhere.

**Comment by TSonono** [comment]
> Any chance you can add a unit test to 
https://github.com/intel/tinycbor/blob/dev/tests/encoder/tst_encoder.cpp?

I can, but I do not have access to the QtTest header. I tried installing Qt but that was not sufficient.

>Also, since this is a new feature, can you re-target the PR to the dev branch?
>
>Finally, as a matter of commit policy, please add a Signed-off-by: to your commit message. I need at least your email -- your name is your option, just make it match the Git commit author.
>
> Oh, please include "Fixes #162" in the commit message somewhere.

Sure.

**Comment by TSonono** [comment]
I redirected the PR to the dev branch and signed the commit. Sadly I could not incorporate any unit tests. I have not worked with QTest before and I don't think I could have made a new case in `encodeVariant` since `QVariant::ByteArray` was already occupied by the encoding of byte strings.

**Comment by thiagomacieira** [comment]
Ok, no problem, I'll add them.

**Comment by sijohans** [comment]
Is this one planned to be merged soon?

**Comment by thiagomacieira** [comment]
Not until someone has time to write the unit test. I promised I would, but I haven't found the time to write it yet.

**Comment by ayechanpyaesonework** [comment]
Is this one planned to be merged soon?

**Comment by shubhamdp** [comment]
Any plans on merging this?

**Comment by thiagomacieira** [comment]
This now needs to be rebased.

**Pull request merged**
